Repository Lenient-Enterprise/CollectiStamp, pull requests merged in 2023-11, with the labels that each got.

#45 refactor: improved catalog looks
  collecti_stamp/templates/product/product_catalog.html
Labels: enhancement

#50 Feature/client corporate branding
  collecti_stamp/templates/base.html
Labels: enhancement

#53 Feature/admin product manegement
  collecti_stamp/product/admin.py
Labels: enhancement, product

#49 Feature/product filter
  collecti_stamp/catalog/urls.py
  collecti_stamp/catalog/views.py
  collecti_stamp/populate_product.json
  collecti_stamp/product/models.py
  collecti_stamp/product/views.py
  collecti_stamp/templates/base.html
  collecti_stamp/templates/finder.html
  collecti_stamp/templates/product/product_catalog.html
Labels: enhancement

#59 Feature/product details
  collecti_stamp/populate_product.json
Labels: product, catalog, 🟢 - Low priority
